// vocabbuilder enumerates every geometrically valid UCI move in chess
// and prints them sorted, one per line.  The line number (0-indexed)
// is the vocab ID.
//
// UCI format: [from_square][to_square][promotion?]
//
//	e2e4, g1f3, e7e8q
//
// Every move is fully specified — no disambiguation ambiguity.
package main

import (
	"fmt"
	"os"
	"sort"
)

func fileChar(f int) byte    { return byte('a' + f) }
func rankChar(r int) byte    { return byte('1' + r) }
func sqStr(f, r int) string  { return string([]byte{fileChar(f), rankChar(r)}) }
func inBounds(f, r int) bool { return f >= 0 && f < 8 && r >= 0 && r < 8 }

func main() {
	moves := map[string]bool{}

	add := func(fromF, fromR, toF, toR int) {
		moves[sqStr(fromF, fromR)+sqStr(toF, toR)] = true
	}
	addPromo := func(fromF, fromR, toF, toR int, promo byte) {
		moves[sqStr(fromF, fromR)+sqStr(toF, toR)+string(promo)] = true
	}

	for f := 0; f < 8; f++ {
		for r := 0; r < 8; r++ {
			// --- Knight ---
			for _, d := range [][2]int{
				{1, 2}, {2, 1}, {2, -1}, {1, -2},
				{-1, -2}, {-2, -1}, {-2, 1}, {-1, 2},
			} {
				tf, tr := f+d[0], r+d[1]
				if inBounds(tf, tr) {
					add(f, r, tf, tr)
				}
			}

			// --- King (1-square moves) ---
			for _, d := range [][2]int{
				{1, 1}, {1, 0}, {1, -1}, {0, 1},
				{0, -1}, {-1, 1}, {-1, 0}, {-1, -1},
			} {
				tf, tr := f+d[0], r+d[1]
				if inBounds(tf, tr) {
					add(f, r, tf, tr)
				}
			}

			// --- Rook / Queen (straight lines) ---
			for _, d := range [][2]int{{1, 0}, {-1, 0}, {0, 1}, {0, -1}} {
				tf, tr := f+d[0], r+d[1]
				for inBounds(tf, tr) {
					add(f, r, tf, tr)
					tf += d[0]
					tr += d[1]
				}
			}

			// --- Bishop / Queen (diagonals) ---
			for _, d := range [][2]int{{1, 1}, {1, -1}, {-1, 1}, {-1, -1}} {
				tf, tr := f+d[0], r+d[1]
				for inBounds(tf, tr) {
					add(f, r, tf, tr)
					tf += d[0]
					tr += d[1]
				}
			}

			// --- White pawns (ranks 2-7, indices 1-6) ---
			if r >= 1 && r <= 6 {
				// Non-promoting push (from ranks 2-6 → ranks 3-7)
				if r <= 5 {
					add(f, r, f, r+1)
				}
				// Double push from rank 2 (index 1)
				if r == 1 {
					add(f, r, f, r+2)
				}
				// Non-promoting captures
				if r <= 5 {
					if f > 0 {
						add(f, r, f-1, r+1)
					}
					if f < 7 {
						add(f, r, f+1, r+1)
					}
				}
				// Promotion from rank 7 (index 6) → rank 8 (index 7)
				if r == 6 {
					for _, p := range []byte{'q', 'r', 'b', 'n'} {
						addPromo(f, r, f, r+1, p)
						if f > 0 {
							addPromo(f, r, f-1, r+1, p)
						}
						if f < 7 {
							addPromo(f, r, f+1, r+1, p)
						}
					}
				}
			}

			// --- Black pawns (ranks 7-2, indices 6-1) ---
			if r >= 1 && r <= 6 {
				// Non-promoting push (from ranks 7-3 → ranks 6-2)
				if r >= 2 {
					add(f, r, f, r-1)
				}
				// Double push from rank 7 (index 6)
				if r == 6 {
					add(f, r, f, r-2)
				}
				// Non-promoting captures
				if r >= 2 {
					if f > 0 {
						add(f, r, f-1, r-1)
					}
					if f < 7 {
						add(f, r, f+1, r-1)
					}
				}
				// Promotion from rank 2 (index 1) → rank 1 (index 0)
				if r == 1 {
					for _, p := range []byte{'q', 'r', 'b', 'n'} {
						addPromo(f, r, f, r-1, p)
						if f > 0 {
							addPromo(f, r, f-1, r-1, p)
						}
						if f < 7 {
							addPromo(f, r, f+1, r-1, p)
						}
					}
				}
			}
		}
	}

	// Castling — 2-square king moves not generated by the 1-square king loop
	add(4, 0, 6, 0) // e1g1 white O-O
	add(4, 0, 2, 0) // e1c1 white O-O-O
	add(4, 7, 6, 7) // e8g8 black O-O
	add(4, 7, 2, 7) // e8c8 black O-O-O

	sorted := make([]string, 0, len(moves))
	for m := range moves {
		sorted = append(sorted, m)
	}
	sort.Strings(sorted)

	for _, m := range sorted {
		fmt.Println(m)
	}
	fmt.Fprintf(os.Stderr, "vocab size: %d\n", len(sorted))
}
