"""Composite move vocabulary for non-UCI composite embedding path.

Loads composite_vocab.txt (generated by cmd/compositevocab) and provides:
  - COMPOSITE_TUPLES: Tensor[V, 8]   vocab_id -> 8 feature IDs
  - COMPOSITE_VOCAB_SIZE: int         46512
  - tuples_to_ids_np(features):       vectorized (N,8) -> (N,) vocab IDs

Feature order matches FEATURE_ORDER: piece, from_square, to_square,
capture, promotion, check, castle, player.
"""

from pathlib import Path

import numpy as np
import torch

from sillychess.san_features import FEATURE_SIZES, FEATURE_ORDER

_VOCAB_PATH = Path(__file__).parent.parent / "composite_vocab.txt"


def _load():
    rows = []
    with open(_VOCAB_PATH) as f:
        for line in f:
            parts = line.strip().split('\t')
            if len(parts) == 8:
                rows.append([int(x) for x in parts])
    return np.array(rows, dtype=np.int32)


_TUPLES_NP = _load()
COMPOSITE_TUPLES = torch.from_numpy(_TUPLES_NP).long()
COMPOSITE_VOCAB_SIZE = len(COMPOSITE_TUPLES)

# Flat lookup table: encode 8-feature tuple as single int, index into array.
# Strides computed from feature sizes (exclusive upper bounds).
_MAXES = [FEATURE_SIZES[name] for name in FEATURE_ORDER]
_STRIDES_NP = np.ones(8, dtype=np.int64)
for _i in range(6, -1, -1):
    _STRIDES_NP[_i] = _STRIDES_NP[_i + 1] * _MAXES[_i + 1]
_FLAT_SIZE = int(_STRIDES_NP[0] * _MAXES[0])

_FLAT_LOOKUP = np.full(_FLAT_SIZE, -1, dtype=np.int32)
for _vid in range(COMPOSITE_VOCAB_SIZE):
    _key = int((_TUPLES_NP[_vid].astype(np.int64) * _STRIDES_NP).sum())
    _FLAT_LOOKUP[_key] = _vid

STRIDES = torch.from_numpy(_STRIDES_NP.copy())


def tuples_to_ids_np(feature_ids):
    """Convert (N, 8) int array of feature IDs to (N,) composite vocab IDs.

    Returns -1 for invalid tuples (padding, out-of-vocab).
    Fully vectorized.
    """
    keys = (feature_ids.astype(np.int64) * _STRIDES_NP).sum(axis=-1)
    # Clamp to valid range (pad positions with all-zeros map to key=0 which is fine,
    # but out-of-range keys from corrupted data need guarding)
    safe = np.clip(keys, 0, _FLAT_SIZE - 1)
    return _FLAT_LOOKUP[safe]
