"""UCI move vocabulary for single-head move prediction.

Loads the vocab generated by cmd/vocabbuilder and provides:
  - UCI_MOVES: list[str]         raw index → UCI string (0-1967)
  - UCI_MOVE_TO_ID: dict         UCI string → raw index
  - UCI_VOCAB_SIZE: int          1968 (raw moves only)
  - UCI_LOOKUP: Tensor[65,65,5]  (from_sq_id, to_sq_id, promo_id) → raw vocab_id

Plain-mode token space (for full-game training):
  - PAD_ID=0, BOG_ID=1, EOG_ID=2, then moves at MOVE_OFFSET=3
  - UCI_PLAIN_VOCAB_SIZE: int    1971
  - token_to_uci_id(tok) → raw index or -1 for special tokens
"""

from pathlib import Path

import torch

from sillychess.san_features import FEATURE_SPECS

_VOCAB_PATH = Path(__file__).parent.parent / "uci_vocab.txt"

_SQUARES = FEATURE_SPECS["from_square"]  # [NULL, a1, b1, ..., h8]
_PROMO_TO_UCI = {0: "", 1: "n", 2: "b", 3: "r", 4: "q"}


def _load_vocab():
    with open(_VOCAB_PATH) as f:
        moves = [line.strip() for line in f if line.strip()]
    to_id = {m: i for i, m in enumerate(moves)}
    return moves, to_id


UCI_MOVES, UCI_MOVE_TO_ID = _load_vocab()
UCI_VOCAB_SIZE = len(UCI_MOVES)  # 1968 (raw, no special tokens)

# Special tokens for --uci-plain full-game training
PAD_ID = 0
BOG_ID = 1
EOG_ID = 2
MOVE_OFFSET = 3
UCI_PLAIN_VOCAB_SIZE = UCI_VOCAB_SIZE + MOVE_OFFSET  # 1971

# Precompute lookup table: (from_sq_id, to_sq_id, promo_id) → vocab_id
# from_sq_id / to_sq_id are 1-indexed (0 = NULL pad).
# promo_id: 0=none, 1=N, 2=B, 3=R, 4=Q.
# -1 means invalid / padding.
_lookup = torch.full((65, 65, 5), -1, dtype=torch.long)
for _from_id in range(1, 65):
    _from_sq = _SQUARES[_from_id]
    for _to_id in range(1, 65):
        _to_sq = _SQUARES[_to_id]
        for _promo_id in range(5):
            _uci = _from_sq + _to_sq + _PROMO_TO_UCI[_promo_id]
            if _uci in UCI_MOVE_TO_ID:
                _lookup[_from_id, _to_id, _promo_id] = UCI_MOVE_TO_ID[_uci]
UCI_LOOKUP = _lookup


_UCI_LOOKUP_CACHE = {}

def batch_to_uci_ids(from_sq_ids, to_sq_ids, promo_ids):
    """Vectorised: (B, T) long tensors → (B, T) UCI vocab IDs.

    Invalid / padding positions get -1.  Use .clamp(min=0) if you need
    non-negative indices before gather, and mask with (ids >= 0).
    Result is on the same device as inputs.
    """
    device = from_sq_ids.device
    if device not in _UCI_LOOKUP_CACHE:
        _UCI_LOOKUP_CACHE[device] = UCI_LOOKUP.to(device)
    return _UCI_LOOKUP_CACHE[device][from_sq_ids, to_sq_ids, promo_ids]


def uci_id_to_move(uci_id):
    """Convert a raw vocab index back to a UCI string, or None."""
    if 0 <= uci_id < UCI_VOCAB_SIZE:
        return UCI_MOVES[uci_id]
    return None


def token_to_uci_id(token_id):
    """Convert a plain-mode token ID to a raw UCI vocab index, or -1."""
    if token_id >= MOVE_OFFSET:
        return token_id - MOVE_OFFSET
    return -1


def token_to_uci_str(token_id):
    """Convert a plain-mode token ID to a UCI string, or None."""
    raw = token_to_uci_id(token_id)
    if raw >= 0:
        return uci_id_to_move(raw)
    return None
